version: 2.1
jobs:
  build:
    docker:
      - image: cimg/php:7.4.30-browsers
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
          version: 20.10.14
      - run:
          name: Install requirements
          command: |
            sudo apt-get update -y
            sudo apt install -y libmagickwand-dev jq
            echo '\n' | sudo pecl install imagick
      - run:
          name: Build PHP SDK 
          command: |
            sh fetch.sh
            cd processmaker
            composer install
            php artisan processmaker:sdk php ./sdk-php
            cd ..
      - run:
          name: Build Docker Image
          command: |
            sh build.sh
workflow:
  build-executor:
    jobs:
      - build
