version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
          version: 20.10.14
      - run:
          name: Build Docker Image
          command: |
            sh build.sh
workflow:
  build-executor:
    jobs:
      - build
