version: 2.1
orbs:
  snyk: snyk/snyk@1.1.2
jobs:
  build:
    docker:
      - image: cimg/php:7.4.30-browsers
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
          version: 20.10.14
      - run:
          name: Install requirements
          command: |
            sudo apt-get update -y
            sudo apt install -y libmagickwand-dev jq
            echo '\n' | sudo pecl install imagick
      - run:
          name: Build PHP SDK 
          command: |
            sh fetch.sh
            cd processmaker
            composer install
            php artisan processmaker:sdk php ./sdk-php
            cd ..
      - run:
          name: Build Docker Image
          command: |
            sh build.sh
      - snyk/scan:
          docker-image-name: '$SDK_IMAGE'
          severity-threshold: high
          fail-on-issues: true
          monitor-on-build: false
workflow:
  build-executor:
    jobs:
      - build
