version: 2.1
jobs:
  build:
    docker:
      - name: remotedocker
        image: docker:20-dind
        environment:
          DOCKER_TLS_CERTDIR: ''
      - image: cimg/base:2022.05

    steps:
      - checkout
      - run:
          name: Build Docker Image
          command: |
            sh build.sh
workflow:
  build-executor:
    jobs:
      - build
